blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ DÃºvidas sobre o repositÃ³rio
    url: https://github.com/DevOps-Brasil/Vagas/discussions
    about: Use as discussÃµes para tirar dÃºvidas sobre o repositÃ³rio
